# Generated by Django 3.2.3 on 2024-09-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='weight',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measuring_value',
            field=models.CharField(default='г', max_length=150),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
