# Generated by Django 3.2.3 on 2024-09-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tag_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measuring_value',
            new_name='measuring_unit',
        ),
    ]
