# Generated by Django 3.2.3 on 2024-09-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_measuring_value_ingredient_measuring_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measuring_unit',
            new_name='mesurement_unit',
        ),
    ]
