# Generated by Django 3.2.3 on 2024-09-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_mesurement_unit_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time',
            new_name='cooking_time',
        ),
    ]
