# Generated by Django 3.2.3 on 2024-09-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_time_recipe_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
