# Generated by Django 3.2.3 on 2024-09-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsinrecipe',
            old_name='weight',
            new_name='amount',
        ),
    ]
