# Generated by Django 3.2.3 on 2024-09-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ingredientsinrecipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.IngredientsInRecipe', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
