# Generated by Django 3.2.3 on 2024-10-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipe',
            old_name='in_cart',
            new_name='is_in_shopping_cart',
        ),
    ]
