# Generated by Django 3.2.3 on 2024-10-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_in_cart_userrecipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecipe',
            old_name='is_in_shopping_cart',
            new_name='in_cart',
        ),
    ]
