# Generated by Django 3.2.3 on 2024-09-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название рецепта'),
        ),
    ]
