# Generated by Django 3.2.3 on 2024-09-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240917_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(default='False', verbose_name='Находится ли рецепт в корзине'),
        ),
    ]
