# Generated by Django 3.2.3 on 2024-09-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='in_cart',
        ),
    ]
