version: '3'

volumes:
  pg_data_production:
  static_volume:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: artemproyd/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media:/app/media/
    depends_on:
      - db
  frontend:
    image: artemproyd/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: artemproyd/foodgram_nginx
    env_file: .env
    depends_on:
      - frontend
      - backend
    volumes:
      - static_volume:/static/
      - media:/media/
    ports:
      - 8000:80

