# Generated by Django 3.2.3 on 2024-10-08 07:39

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Данное имя занято'}, max_length=150, unique=True, validators=[api.validators.validate_name], verbose_name='Имя пользователя'),
        ),
    ]
