# Generated by Django 3.2.3 on 2024-08-24 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Данное имя занято'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Ваше сообщение об ошибке', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
